environment: "Staging"

secret:
  name: mediaingest-k8s-secret

secrets:
  s3AccessKey: test-bucket-access-key
  s3SecretKey: test-bucket-secret-key
  connectionStringKey: userservice-db-conn 

volumeMounts:
  - name: config-volume
    mountPath: /app/appsettings.Staging.json
    subPath: appsettings_override.json

appConfig:
  S3:
    Host: "storage.googleapis.com"
    AccessKey: ""
    SecretKey: ""
    BucketName: "amplify-media-test"
    UseSsl: true
  YtDlp:
    YoutubeDlPath: "/opt/homebrew/bin/yt-dlp"
  MediaIngest:
    BasePath: "/media"
  Jwt:
    Issuer: "http://userservice.test-env.svc.cluster.local/userservice/api/auth"
    Audience: "MyAppDevelopmentUsers"