environment: "Development"

appConfig:
  ConnectionStrings:
    UserServiceDb: "Host=host.minikube.internal;Port=6433;Database=myDb;Username=dev_user;Password=dev_password;"

  Logging:
    LogLevel:
      Default: Information
      Microsoft: Warning

  MailOptions:
    ApiKey: ""

  Jwt:
    Key: "DevelopmentSecretKeyForJwtTokenGeneration"
    Issuer: "MyAppDevelopment"
    Audience: "MyAppDevelopmentUsers"
    PrivateKeyPem: ""

  MyCookies:
    AccessTokenCookieName: MyAppAccessToken
    RefreshTokenCookieName: MyAppRefreshToken

  CorsOptions:
    AllowedOrigins:
      - "http://dev.amplify-vkr.example.com"
    DefaultPolicyName: DevelopmentCorsPolicy

  Frontend:
    Url: "http://dev.amplify-vkr.example.com"
    EmailConfirmedPath: "/api/index.html?url=/api/specification.json"
    EmailConfirmationPath: "/confirm-email"
    PasswordResetPath: "/reset-password"

  ExternalUrls:
    MediaServiceApi: "https://media.my-prod-site.com"
    
  InternalUrls:
    MediaServiceInternalBaseUrl: "http://media-service.default.svc.cluster.local"

