environment: Development

secrets:
  defaultConnectionString:
    key: publisher-db-conn-test
  hangfireConnectionString:
    key: publisher-hangfire-db-conn-test

volumeMounts:
  - name: config-volume
    mountPath: /app/appsettings.Development.json
    subPath: appsettings_override.json

appConfig:
  Logging:
    LogLevel:
      Default: "Information"
      Microsoft: "Warning"
      Microsoft.Hosting.Lifetime: "Information"
  MediaService:
    BaseUrl: "http://host.minikube.internal:6001"
  InstagramApiOptions:
    AppId: "instagram_app_id"
    AppSecret: "instagram_app_secret"
    RedirectUri: "http://host.minikube.internal:6001/auth/instagram/callback"
    ApiVersion: "v22.0"
    DailyLimit: 200
    BaseGraphHostUrl: "https://graph.facebook.com/"
  RabbitMQOptions:
    Host: "host.minikube.internal"
    Username: "guest"
    Password: "guest"
  ExternalUrls:
    MediaServiceApi: "http://host.minikube.internal:6001"
  Jwt:
    Issuer: "http://userservice.default.svc.cluster.local/userservice/api/auth"
    Audience: "MyAppDevelopmentUsers"
  PublisherOptions:
    BasePath: /publisher