environment: Staging

secrets:
  defaultConnectionString:
    key: publisher-db-conn-test
  hangfireConnectionString:
    key: publisher-hangfire-db-conn-test
  rabbitMqConnection:
    key: rabbitmq-test
  tikTokClientKey:
    key: tiktok-client-key-sandbox
  tikTokClientSecret:
    key: tiktok-client-secret-sandbox

volumeMounts:
  - name: config-volume
    mountPath: /app/appsettings.Staging.json
    subPath: appsettings_override.json

appConfig:
  Logging:
    LogLevel:
      Default: "Information"
      Microsoft: "Warning"
      Microsoft.Hosting.Lifetime: "Information"
  MediaService:
    BaseUrl: "http://mediaingest.test-env.svc.cluster.local"
  InstagramApiOptions:
    AppId: "instagram_app_id"
    AppSecret: "instagram_app_secret"
    RedirectUri: "http://host.minikube.internal:6001/auth/instagram/callback"
    ApiVersion: "v22.0"
    DailyLimit: 200
    BaseGraphHostUrl: "https://graph.facebook.com/"
  RabbitMQOptions:
    Host: ""
    Username: ""
    Password: ""
  ExternalUrls:
    MediaServiceApi: "http://host.minikube.internal:6001"
  Jwt:
    Issuer: "http://userservice.test-env.svc.cluster.local/userservice/api/auth"
    Audience: "MyAppDevelopmentUsers"
  PublisherOptions:
    BasePath: /publisher
  CorsOptions:
    AllowedOrigins:
      - "http://localhost:3000"
    DefaultPolicyName: DevelopmentCorsPolicy
  Frontend:
    BaseUrl: "http://localhost:3000"
    ConnectionsPath: "/connections"