apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}          
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store            
  target:
    name: {{ .Values.secret.name }}
    creationPolicy: Owner
  data:
  - secretKey: ConnectionStrings__Default
    remoteRef:
      key: {{ .Values.secrets.defaultConnectionString.key }}
      {{- if .Values.secrets.defaultConnectionString.version }}
      version: {{ .Values.secrets.defaultConnectionString.version }}
      {{- end }}
  - secretKey: ConnectionString__Hangfire
    remoteRef:
      key: {{ .Values.secrets.hangfireConnectionString.key }}
      {{- if .Values.secrets.hangfireConnectionString.version }}
      version: {{ .Values.secrets.hangfireConnectionString.version }}
      {{- end }}