apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}          
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.secretStore.name }}           
  target:
    name: {{ .Values.secret.name }}
    creationPolicy: Owner
  data:
  - secretKey: RabbitMQ__Url
    remoteRef:
      key: {{ .Values.secrets.rabbitMqConnection.key }}
      {{- if .Values.secrets.rabbitMqConnection.version }}
      version: {{ .Values.secrets.rabbitMqConnection.version }}
      {{- end}}