apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mediaingest-external-secrets
spec:
  refreshInterval: 1h            
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store            
  target:
    name: {{ .Values.secret.name }}
    creationPolicy: Owner
  data:
  - secretKey: S3__AccessKey 
    remoteRef:
      key: {{ .Values.secrets.s3AccessKey }}
  - secretKey: S3__SecretKey
    remoteRef:
      key: {{ .Values.secrets.s3SecretKey }}